#' @title
#'   Create a new Monty Hall Problem game.
#'
#' @description
#'   `create_game()` generates a new game that consists of two doors
#'   with goats behind them, and one with a car.
#'
#' @details
#'   The game setup replicates the game on the TV show "Let's
#'   Make a Deal" where there are three doors for a contestant
#'   to choose from, one of which has a car behind it and two
#'   have goats. The contestant selects a door, then the host
#'   opens a door to reveal a goat, and then the contestant is
#'   given an opportunity to stay with their original selection
#'   or switch to the other unopened door. There was a famous
#'   debate about whether it was optimal to stay or switch when
#'   given the option to switch, so this simulation was created
#'   to test both strategies.
#'
#' @param ... no arguments are used by the function.
#'
#' @return The function returns a length 3 character vector
#'   indicating the positions of goats and the car.
#'
#' @examples
#'   create_game()
#'
#' @export
create_game <- function( num.goats = 2 ){
  a.game <- sample( x=c("goat","goat","car"), size=3, replace=F )
  return( a.game )
}



#' @title
#'   Select an initial door in the Monty Hall game.
#'
#' @description
#'   `select_door()` simulates a contestant making their initial selection
#'   of one of the three doors at the start of the game.
#'
#' @details
#'   In the Monty Hall Problem, the contestant must choose one of three
#'   closed doors before any goats are revealed. This choice represents
#'   the initial state of the simulation, which will later be evaluated
#'   against the host's revealed goat door.
#'
#' @param ... no arguments are used by the function.
#'
#' @return The function returns a single integer (1, 2, or 3) representing
#'   the index of the selected door.
#'
#' @examples
#'   select_door()
#'
#' @export
select_door <- function(game = create_game()) {
  doors <- c(1,2,3)
  a.pick <- sample( doors, size=1 )
  return( a.pick )  # number between 1 and 3
}



#' @title
#'   Open a goat door in the Monty Hall game.
#'
#' @description
#'   `open_goat_door()` simulates the host opening a door to reveal a goat
#'   after the contestant has made their initial door selection.
#'
#' @details
#'   The host knows what is behind each door and must follow specific rules:
#'   the host must always open a door containing a goat, and it can never be
#'   the door that the contestant initially selected. If the contestant
#'   initially chose the car, the host randomly picks one of the two remaining
#'   goat doors to open. If the contestant chose a goat, the host opens the
#'   only other door containing a goat.
#'
#' @param game A character vector of length 3 representing the game board setup
#'   (e.g., generated by `create_game()`).
#' @param a.pick A single integer (1, 2, or 3) representing the contestant's
#'   initial choice of door (e.g., generated by `select_door()`).
#'
#' @return The function returns a single integer (1, 2, or 3) representing
#'   the index of the door containing a goat opened by the host.
#'
#' @examples
#'   this_game <- create_game()
#'   my_pick <- select_door()
#'   open_goat_door( game = this_game, a.pick = my_pick )
#'
#' @export
open_goat_door <- function(game = create_game(), a.pick = select_door(game)) {
  doors <- c(1,2,3)
  # if contestant selected car,
  # randomly select one of two goats
  if( game[ a.pick ] == "car" )
  {
    goat.doors <- doors[ game != "car" ]
    opened.door <- sample( goat.doors, size=1 )
  }
  if( game[ a.pick ] == "goat" )
  {
    opened.door <- doors[ game != "car" & doors != a.pick ]
  }
  return( opened.door ) # number between 1 and 3
}




#' @title
#'   Determine the final door choice based on strategy.
#'
#' @description
#'   `change_door()` simulates the contestant's decision to either stay with
#'   their initial door choice or switch to the remaining unopened door.
#'
#' @details
#'   After the host opens a door to reveal a goat, the contestant is faced
#'   with a choice. If the contestant decides to stay (`stay = TRUE`), their
#'   final choice remains their initial pick. If they decide to switch
#'   (`stay = FALSE`), their final choice becomes the one remaining closed
#'   door that was neither their initial pick nor the door opened by the host.
#'
#' @param stay A logical value (`TRUE` or `FALSE`) indicating whether the
#'   contestant stays with their original selection. Defaults to `TRUE`.
#' @param opened.door A single integer (1, 2, or 3) representing the index
#'   of the door containing a goat opened by the host.
#' @param a.pick A single integer (1, 2, or 3) representing the contestant's
#'   initial door selection.
#'
#' @return The function returns a single integer (1, 2, or 3) representing
#'   the index of the contestant's final door choice.
#'
#' @examples
#'   this_game <- create_game()
#'   my_pick <- select_door()
#'   goat_door <- open_goat_door( game = this_game, a.pick = my_pick )
#'
#'   # Strategy: Stay
#'   change_door( stay = TRUE, opened.door = goat_door, a.pick = my_pick )
#'
#'   # Strategy: Switch
#'   change_door( stay = FALSE, opened.door = goat_door, a.pick = my_pick )
#'
#' @export
change_door <- function( stay=T, opened.door, a.pick )
{
  doors <- c(1,2,3)

  if( stay )
  {
    final.pick <- a.pick
  }
  if( ! stay )
  {
    final.pick <- doors[ doors != opened.door & doors != a.pick ]
  }

  return( final.pick )  # number between 1 and 3
}




#' @title
#'   Determine if the contestant won the game.
#'
#' @description
#'   `determine_winner()` evaluates whether the contestant's final door choice
#'   contains the car ("WIN") or a goat ("LOSE").
#'
#' @details
#'   This function serves as the conclusion of the Monty Hall simulation. It maps
#'   the contestant's final selected door index back to the underlying game
#'   setup vector to check if the final choice matched the winning prize.
#'
#' @param final.pick A single integer (1, 2, or 3) representing the index of
#'   the contestant's final door choice (e.g., generated by `change_door()`).
#' @param game A character vector of length 3 representing the game board setup
#'   (e.g., generated by `create_game()`).
#'
#' @return The function returns a single character string: either `"WIN"` if the
#'   final choice hides a car, or `"LOSE"` if it hides a goat.
#'
#' @examples
#'   this_game <- create_game()
#'   my_pick <- select_door()
#'   goat_door <- open_goat_door( game = this_game, a.pick = my_pick )
#'   final_pick <- change_door( stay = FALSE, opened.door = goat_door, a.pick = my_pick )
#'
#'   determine_winner( final.pick = final_pick, game = this_game )
#'
#' @export
determine_winner <- function( final.pick, game )
{
  if( game[ final.pick ] == "car" )
  {
    return( "WIN" )
  }
  if( game[ final.pick ] == "goat" )
  {
    return( "LOSE" )
  }
}






#' @title
#'   Play a complete single game of the Monty Hall Problem.
#'
#' @description
#'   `play_game()` acts as a wrapper function that automatically sequences a new game
#'   setup, initial door selection, host actions, and evaluates outcomes for both
#'   the "stay" and "switch" strategies simultaneously.
#'
#' @details
#'   This function simplifies simulation studies by bundling the entire sequence
#'   of gameplay steps into a single call. It sets up the board, picks a door,
#'   reveals a goat, applies both choice strategies to that exact same layout,
#'   and records the results.
#'
#' @param ... no arguments are used by the function.
#'
#' @return The function returns a data frame with two rows and two columns:
#'   \describe{
#\('     \item{strategy}{A character vector indicating the player choice ("stay" or "switch").}\)
#\('     \item{outcome}{A character vector indicating the final result ("WIN" or "LOSE").}\)
#'   }
#'
#' @examples
#'   play_game()
#'
#' @export
play_game <- function( )
{
  new.game <- create_game()
  first.pick <- select_door()
  opened.door <- open_goat_door( new.game, first.pick )

  final.pick.stay <- change_door( stay=T, opened.door, first.pick )
  final.pick.switch <- change_door( stay=F, opened.door, first.pick )

  outcome.stay <- determine_winner( final.pick.stay, new.game  )
  outcome.switch <- determine_winner( final.pick.switch, new.game )

  strategy <- c("stay","switch")
  outcome <- c(outcome.stay,outcome.switch)
  game.results <- data.frame( strategy, outcome,
                              stringsAsFactors=F )
  return( game.results )
}







#' @title
#'   Simulate multiple Monty Hall games and calculate win rates.
#'
#' @description
#'   `play_n_games()` loops through a specified number of game iterations,
#'   tracking results for both stay and switch strategies, and outputs a
#'   proportional success table.
#'
#' @details
#'   This function uses a loop to repeatedly call `play_game()`. It collects
#'   the results of each iteration, binds them together into a single
#'   data frame using `dplyr::bind_rows()`, calculates the conditional
#'   probability of winning given each strategy, and prints a cleanly rounded
#'   summary table to the console.
#'
#' @param n An integer specifying the total number of games to simulate.
#'   Defaults to `100`.
#'
#' @return The function returns a data frame containing the aggregated
#'   results of all simulated games, featuring a `strategy` column and an
#'   `outcome` column.
#'
#' @examples
#'   # Run a small simulation of 10 games
#'   play_n_games( n = 10 )
#'
#'   # Run a standard simulation of 500 games
#'   play_n_games( n = 500 )
#'
#' @importFrom dplyr bind_rows
#' @export
play_n_games <- function( n=100 )
{

  library( dplyr )
  results.list <- list()   # collector
  loop.count <- 1

  for( i in 1:n )  # iterator
  {
    game.outcome <- play_game()
    results.list[[ loop.count ]] <- game.outcome
    loop.count <- loop.count + 1
  }

  results.df <- dplyr::bind_rows( results.list )

  return( results.df )

}
